export enum EReduxUserAssetsActions {
  UPDATE = "UPDATE_ASSET",
  UPDATE_PRICE = "UPDATE_ASSET_PRICE",
  SET = "SET_ASSET",
}

export enum EReduxAuthActions {
  SET = "SET_AUTH_DETAILS",
  REMOVE = "REMOVE_AUTH_DETAILS",
}

export enum EReduxCustomAssetActions {
  ADD = "ADD_CUSTOM_ASSET",
  UPDATE = "UPDATE_CUSTOM_ASSET",
  SET_ALL = "SET_ALL_CUSTOM_ASSETS",
  REMOVE = "REMOVE_CUSTOM_ASSET",
  DELETE_ALL = "DELETE_ALL_CUSTOM_ACTIONS_LOGOUT",
}
